[package]
name = "calc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
az = "1.2.1"
rug = { version = "1.22.0", features = ["complex","integer"] }
rustyline = "12.0.0"
